packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - aws-sdk
  - esbuild
  - msgpackr-extract
  - prisma
  - puppeteer
  - sharp
  - unrs-resolver
